ipfs/ipld-explorer-components

- src/lib/normalise-dag-node.js
- src/lib/normalize-dag-node.test.js
Also added some tests for the normalization of dag-cbor types
See: https://github.com/ipfs-shipyard/ipld-explorer/issues/46
> fix: fix empty arrays throwing error in dag-cbor types

- src/components/StartExploringPage.js
Tweak the start page to make more sense visually on very large screens
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>
> fix: tweak layout for the larger screen

- src/components/cid-info/CidInfo.js
Old link https://github.com/multiformats/multihash/blob/master/hashtable.csv doesn't work.
I suppose the correct one is https://github.com/multiformats/multicodec/blob/master/table.csv
Maybe it is better to point to a documentation page instead of a github link?
> Fixed dead link to the list of hashes

- src/bundles/explore.js
IPLD formats are now extracted so the app should pass the ones that it wants to support.
> feat: extract ipld formats

- src/lib/normalise-dag-node.js
This guarantees backward compatibility with old dag-cbor links.
> fix: backward compat with dag-cbor

- package.json
- src/components/object-info/LinksTable.js
Not sure if this is too hacky a suggestion, but enables full-height link tables by way of nesting `math`:
`tableHeight` is the greater of either 370px or (_the lesser of either "window height less page header height" or "the number of rows x row height plus table header height"_)
Note that 370px is the current max height.
Closes https://github.com/ipfs-shipyard/ipld-explorer/issues/53.
> fix: show as many node links as height allows

- package-lock.json
- package.json
- src/bundles/explore.js
- src/components/StartExploringPage.js
- src/components/object-info/ObjectInfo.js
- src/lib/cid.js
- src/lib/resolve-ipld-path.js
- src/lib/resolve-ipld-path.test.js
This PR partially  reverts https://github.com/ipfs/ipld-explorer-components/pull/287 because `/api/v0/dag` in go-ipfs do not implement latest IPLD features  yet, and ipfs-http-client delegates path traversal and resolution to go-ipfs, so codecs in JS are never used, and what is in go-ipfs under `dag` commands  is not enough.
By reverting to standalone js-ipld we decouple IPLD explorer from what  is available in go-ipfs – we simply fetch raw block and do all decoding  the old way, in JS.
We will revisit this in the future, after IPLD Prime work lands in  go-ipfs, but for now this is the only way to fix IPLD Explorer to work  against go-ipfs backend.
> fix: restore standalone js-ipld instance

- src/components/object-info/LinksTable.css
- src/components/object-info/LinksTable.js
This PR overrides the default ellipsis truncation for CID rows in virtualized tables. This allows the user to be able to scroll to see the last bytes of a CID in the Explore Table.
Fixes  https://github.com/ipld/explore.ipld.io/issues/71
> Add CID row styling to allow scrolling and remove ellipsis

- README.md
current contributing.md link returns 404
Related: https://github.com/ipfs/ipfs-companion/pull/1038
> docs: fix community CONTRIBUTING.md links

- package-lock.json
- package.json
- src/bundles/explore.js
- src/components/explore/IpldCarExploreForm.js
This is an extension to the previous PR to support CAR import.
+ The in-memory js-ipfs requires the CAR file (stream) to be an 'iterable' object. This means we need to convert the ReadableStream to AsyncIterable.
+ Instead of showing `Explore` button when CAR import is chosen, we instead should just consume the CAR directly and import the dag file as soon as the user uploads the file.
https://github.com/ipfs/ipld-explorer-components/pull/313
https://github.com/ipld/explore.ipld.io/pull/82
> fix: convert car stream to iterable

- package-lock.json
- package.json
- src/bundles/explore.js
I just plugged the new format using this marvellous converter: https://github.com/ipld/js-blockcodec-to-ipld-format
License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>
> feat: support dag-json

- .github/workflows/js-test-and-release.yml
> fix: use nodejs-16 in CI

- README.md
ipld-explorer-lib => ipld-explorer-components
> docs: fix wrong style referencing paths in cra example

- .storybook/preview.ts
- package.json
- vite.config.ts
- fix: rename storybook build script
- fix: storybook build and npm run dev
fixes fleek failure for storybook:
> fix: storybook build

- public/locales/en/explore.json
- src/bundles/explore.js
- src/components/ExplorePage.jsx
- src/components/explore/IpldExploreErrorComponent.tsx
- src/lib/errors.ts
- src/lib/get-raw-block.ts
PR to address issue pointed out in explore.ipld.io PR comment: https://github.com/ipld/explore.ipld.io/pull/119#pullrequestreview-1519319888
> fix: fetch timeout has better error UX

- src/lib/init-helia.ts
This was tested on ipfs-webui via the following patch:
```diff
diff --git a/node_modules/ipld-explorer-components/dist/lib/init-helia.js b/node_modules/ipld-explorer-components/dist/lib/init-helia.js
index e1204a1..53b6218 100644
--- a/node_modules/ipld-explorer-components/dist/lib/init-helia.js
+++ b/node_modules/ipld-explorer-components/dist/lib/init-helia.js
@@ -14,6 +14,17 @@ import { trustlessGateway } from 'helia/block-brokers';
import { createLibp2p } from 'libp2p';
import { getHashersForCodes } from './hash-importer.js';
import { addDagNodeToHelia } from '../lib/helpers.js';
+
+function areRemoteGatewaysEnabled () {
+  const localStorageKey = 'explore.ipld.gatewayEnabled'
+  console.info(
+    `🎛️ Customise whether ipld-explorer-components fetches content from gateways by setting …
```
> feat: re-allow disabling of remote gateways

- src/components/explore/IpldExploreForm.jsx
Now empty searches can not be executed now.
Approach:
- Implemented a if check on the input string
- which updates the state of the search bar component for rendering the error message.
- Additionally changed the outline and placeholder if there is any empty search.
> CID search fix: empty searches are blocked

- .aegir.js
- .storybook/main.ts
- README.md
- package-lock.json
- package.json
- src/lib/hash-importer.ts
- src/lib/init-helia.ts
- **feat: enable blake2b-256 and -512 hashers**
- **chore: npx update-browserslist-db@latest**
- **test: run storybook stories while testing**
> feat: add blake2b-256 hasher

- README.md
- dev/devPage.jsx
- src/components/StartExploringPage.jsx
- src/lib/explorePageSuggestions.js
StartExploringPage will use the default links if none are provided.
> fix: use default explore links

- package-lock.json
- package.json
- src/lib/hash-importer.ts
- src/lib/init-helia.ts
- **tmp: testing dynamic import**
- **chore: temporarily disable delegated routing**
- **fix: getHashersForCodes handles errors gracefully**
- **fix: revert version, other minor changes**
> fix: local only unless remote is enabled(default)

- package-lock.json
- package.json
- src/bundles/helia.ts
- src/lib/init-helia.ts
- **chore: explainer comments**
- **fix: allowInsecure isn't needed for local gateways**
> fix: explore page can query local kubo

- src/lib/init-helia.ts
I believe Chrome hardcodes `.dev` domains to always use `https` anyway, but other browsers may not do that, and mixed-content failure may occur.
> fix: use delegated routing over https

- src/providers/helia.tsx
* remove useReducer from helia provider to simplify things
* add a new function to helia provider to update kubo options
* Helia provider now checks `kuboGateway` in local storage prior to initializing Helia
> fix: init Helia with localStorage.kuboGateway if they exist

- dev/devPage.tsx
- src/components/ExplorePage.stories.tsx
- src/components/ExplorePage.tsx
- src/components/loader/loader.tsx
- src/providers/explore.tsx
fix: allow explore state to be updated outside of hashchange events
This change allows the explore state to be updated outside of hashchange events. This is useful for cases where:
1. The explore state is updated by a component that is not part of the explore view.
2. The router used by the consuming app does not emit hashchange events.
Fixes https://github.com/ipfs/ipld-explorer-components/issues/455
> fix: allow explore state to be updated outside of hashchange events

- src/components/object-info/links-table.tsx
- src/lib/init-helia.ts
- src/providers/explore.tsx
- src/providers/helia.tsx
- **fix: setExplorePath doesnt throw for encoded paths**
- **fix: kuboGateway defaults are handled gracefully**
- **chore: move localStorage info log**
- **fix: do not init helia on mount**
related: https://github.com/ipfs/ipfs-webui/pull/2283
> fix: webui consumption

- src/components/object-info/links-table.tsx
- src/lib/helpers.ts
- src/lib/normalise-dag-node.ts
- src/lib/resolve-ipld-path.ts
- **chore: remove unnecessary any cast**
- **chore: fix return type on isTruthy**
- **fix: links without paths can be navigated**
Fixes #461
See description of bug at https://github.com/ipfs/ipld-explorer-components/issues/461#issuecomment-2491610750
> fix: links without paths can be navigated

- src/components/object-info/ObjectInfo.stories.tsx
- src/lib/hash-importer.ts
- test/e2e/edge-cases.test.ts
fix: identity hashes display object info
added story and e2e test
> fix: identity hashes display object info

- README.md
This PR fixes a documentation error in the README where it referenced `devPage.jsx` instead of the correct file `devPage.tsx`.
- Updated the file reference from `./dev/devPage.jsx` to `./dev/devPage.tsx` to match the actual file in the repository
Documentation-only change, verified that the correct file exists in the repository.
> docs: update devPage file reference to .tsx extension
